### ISSUE TITLE
Tagged releases and changelog

### ISSUE THREAD

**Issue by baimafeima** [Katee/quietnet#37]
Could you tag your releases and make the changelog directly visible in your GitHub releases? This would increase transparency for potential users and distribution maintainers. Something like https://skywinder.github.io/github-changelog-generator/ could be used to generate the changelog based on merged PRs and closed issues since the last release tag.

**Comment by Katee** [comment]
This project is a toy, not a in-production open source project. It also hasn't had a commit in 4 years. 

Please consider only making your cut-and-past comment on active repositories.

**Comment by baimafeima** [comment]
> Please consider only making your cut-and-past comment on active repositories.

Thank you for the updates. The purpose of my cut-and-paste comment is to find out whether there is any _active_ development going on. No need to tell me what to do.

**Comment by jamesacampbell** [comment]
@baimafeima she @Katee can do what she wants, she is the owner of the project, and she probably didn't need to reply to you at all but _did you a courtesy_, consider doing the same and peace out.
